# Generated by Django 4.2.30 on 2026-06-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('author', models.CharField(default='Agency Team', max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('image_url', models.CharField(blank=True, help_text='Cover image path or URL', max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('kpi_traffic', models.CharField(blank=True, help_text='e.g. +145% Traffic Increase', max_length=50, null=True)),
                ('kpi_conversion', models.CharField(blank=True, help_text='e.g. +3.2% Conversion Rate', max_length=50, null=True)),
                ('kpi_roi', models.CharField(blank=True, help_text='e.g. 5x Return on Ad Spend', max_length=50, null=True)),
                ('results_detail', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.CharField(max_length=100)),
                ('needs', models.TextField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('lead_type', models.CharField(choices=[('high', 'High Intent'), ('medium', 'Medium Intent'), ('low', 'Low Intent')], default='medium', max_length=10)),
                ('source', models.CharField(choices=[('seo', 'SEO'), ('ads', 'Google Ads'), ('social', 'Social Media'), ('other', 'Other')], default='other', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('problem', models.TextField(help_text='Problem definition for SEO landing page')),
                ('solution', models.TextField(help_text='Solution description')),
                ('process', models.TextField(help_text='Our step-by-step process')),
                ('results', models.TextField(help_text='Expected results/KPIs')),
                ('icon', models.CharField(default='Activity', help_text='Lucide icon identifier', max_length=50)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True)),
            ],
        ),
    ]
